### ISSUE TITLE
Support for laravel 8?

### ISSUE THREAD

**Issue by KaracsonyMarton** [Otisz/Laravel-Billingo#12]

**Comment by Otisz** [comment]
Hello @KoDaFromHills 

Laravel Billingo V2 is currently using Billingo API V1 which is deprecated. We can support L8 until it's shut down.

V3 (current master branch) is a complete rewrite and is already supporting L8, but it has not been released yet, because it's missing documentation for now.

**Comment by Otisz** [comment]
Laravel 8 support: [9463665](https://github.com/Otisz/Laravel-Billingo/commit/94636653fec372c5a99956480193235b7546b8ed).
