### ISSUE TITLE
Support for PHP 8.1? 

### ISSUE THREAD

**Issue by zsoro2** [Otisz/Laravel-Billingo#13]
If you would like to propose new features, please make a pull request.

**Comment by Otisz** [comment]
Yes, but i had no time-energy-motivation combination last year to work in this project.
I will try to find some time in this week.

In the other hand, the `main` branch containts a complete refactor, but it never got a documentation.

**Comment by Otisz** [comment]
From now, in `v2.1.0` composer.json allow PHP8.* and newer Laravel versions up to 10.
But V2 is still lacking of tests, so I can not garantee it will work as intended.

I noticed on Billingo, V2 is not deprecated so I removed this status from the readme.
