### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zsoro2** [Otisz/Laravel-Billingo#9]
Van valami ötleted mitől lehet?

Laravel 6
v2.0

![Screenshot 2020-05-29 at 13 38 58](https://user-images.githubusercontent.com/3978697/83256000-e0bd3100-a1b1-11ea-83a9-0318e806f1a4.png)

**Comment by Otisz** [comment]
Ha nem változtattak valamit a Billingónál, mert ugye most jött ki a V3 API-juk, akkor a JWT generálással lesz problémám.
